backend:
  name: github
  repo: tonyketcham/puerh.wtf
  branch: main

media_folder: 'static/images/uploads'
public_folder: '/images/uploads'
# media_library:
#     config:
#         multiple: true

display_url: puerhwtf.netlify.app

collections:
  - label: 'Tastings'
    name: 'tastings'
    label_singular: 'Tea Tasting'
    description: 'Personal evaluations of teas'
    folder: 'content/tastings'
    create: true
    delete: true
    slug: '{{slug}}'
    identifier_field: 'tea_name'
    summary: '{{year}}-{{month}}-{{day}} | {{fields.tea_name}} | {{fields.season}} {{fields.production_year}}'
    extension: 'md'
    fields:
      - label: 'Tea Name'
        name: 'tea_name'
        widget: 'string'

      - label: 'Tea Genre'
        name: 'genre'
        widget: 'relation'
        collection: 'genres'
        multiple: true
        value_field: 'name'
        search_fields: ['name', 'parent']
        display_fields: ['name']

      - label: 'Cultivar'
        name: 'cultivar'
        widget: 'relation'
        collection: 'cultivars'
        multiple: true
        value_field: 'name'
        search_fields: ['name']
        display_fields: ['name']
        required: false

      - label: 'Origin'
        name: 'origin'
        widget: 'relation'
        collection: 'origins'
        multiple: true
        value_field: 'location'
        search_fields: ['location', 'municipality', 'country']
        display_fields: ['location', 'municipality', 'country']
        required: false

      - label: 'Season'
        name: 'season'
        widget: 'string'
        required: false

      - label: 'Production Year'
        name: 'production_year'
        widget: 'number'
        default: 2020
        required: false

      - label: 'Picking'
        name: 'picking'
        widget: 'string'
        required: false

      - label: 'Elevation (Ft)'
        name: 'elevation'
        widget: 'number'
        required: false

      - label: 'Aging Conditions'
        name: 'aging_conditions'
        widget: 'string'
        required: false

      - label: 'Vendor'
        name: 'vendor'
        widget: 'relation'
        collection: 'vendors'
        multiple: true
        value_field: 'slug'
        search_fields: ['name', 'location', 'municipality', 'country']
        display_fields: ['name', 'location', 'municipality', 'country']
        required: false

      - label: 'Purchase Link'
        name: 'purchase_link'
        widget: 'string'
        required: false

      - label: 'Excerpt'
        name: 'excerpt'
        widget: 'string'

      - label: 'Publish Date'
        name: 'date'
        widget: 'datetime'

      - label: 'Flavor Axes'
        name: 'flavor_axes'
        widget: 'object'
        fields:
          - label: 'Vegetal'
            name: 'vegetal'
            widget: 'object'
            fields:
              - label: 'Start'
                name: 'start'
                widget: 'number'
                default: 0
                min: 0
                max: 10

              - label: 'Finish'
                name: 'finish'
                widget: 'number'
                default: 0
                min: 0
                max: 10

          - label: 'Floral'
            name: 'floral'
            widget: 'object'
            fields:
              - label: 'Start'
                name: 'start'
                widget: 'number'
                default: 0
                min: 0
                max: 10

              - label: 'Finish'
                name: 'finish'
                widget: 'number'
                default: 0
                min: 0
                max: 10

          - label: 'Fruits'
            name: 'fruits'
            widget: 'object'
            fields:
              - label: 'Start'
                name: 'start'
                widget: 'number'
                default: 0
                min: 0
                max: 10

              - label: 'Finish'
                name: 'finish'
                widget: 'number'
                default: 0
                min: 0
                max: 10

          - label: 'Spices'
            name: 'spices'
            widget: 'object'
            fields:
              - label: 'Start'
                name: 'start'
                widget: 'number'
                default: 0
                min: 0
                max: 10

              - label: 'Finish'
                name: 'finish'
                widget: 'number'
                default: 0
                min: 0
                max: 10

          - label: 'Earth'
            name: 'earth'
            widget: 'object'
            fields:
              - label: 'Start'
                name: 'start'
                widget: 'number'
                default: 0
                min: 0
                max: 10

              - label: 'Finish'
                name: 'finish'
                widget: 'number'
                default: 0
                min: 0
                max: 10

          - label: 'Wood'
            name: 'wood'
            widget: 'object'
            fields:
              - label: 'Start'
                name: 'start'
                widget: 'number'
                default: 0
                min: 0
                max: 10

              - label: 'Finish'
                name: 'finish'
                widget: 'number'
                default: 0
                min: 0
                max: 10

          - label: 'Nuts/Roast'
            name: 'nuts_roast'
            widget: 'object'
            fields:
              - label: 'Start'
                name: 'start'
                widget: 'number'
                default: 0
                min: 0
                max: 10

              - label: 'Finish'
                name: 'finish'
                widget: 'number'
                default: 0
                min: 0
                max: 10

          - label: 'Cream'
            name: 'cream'
            widget: 'object'
            fields:
              - label: 'Start'
                name: 'start'
                widget: 'number'
                default: 0
                min: 0
                max: 10

              - label: 'Finish'
                name: 'finish'
                widget: 'number'
                default: 0
                min: 0
                max: 10

          - label: 'Stone'
            name: 'stone'
            widget: 'object'
            fields:
              - label: 'Start'
                name: 'start'
                widget: 'number'
                default: 0
                min: 0
                max: 10

              - label: 'Finish'
                name: 'finish'
                widget: 'number'
                default: 0
                min: 0
                max: 10

          - label: 'Umami'
            name: 'umami'
            widget: 'object'
            fields:
              - label: 'Start'
                name: 'start'
                widget: 'number'
                default: 0
                min: 0
                max: 10

              - label: 'Finish'
                name: 'finish'
                widget: 'number'
                default: 0
                min: 0
                max: 10

      - label: 'Experience Notes'
        name: 'notes'
        widget: 'object'
        summary: '{{taste}} -- {{cha_qi}}'
        collapsed: true
        fields:
          - label: 'Dry Leaf Nose'
            name: 'dry_leaf_nose'
            widget: 'string'

          - label: 'Wet Leaf Nose'
            name: 'wet_leaf_nose'
            widget: 'string'

          - label: 'Mouthfeel'
            name: 'mouthfeel'
            widget: 'string'

          - label: 'Taste'
            name: 'taste'
            widget: 'string'

          - label: 'Finish'
            name: 'finish'
            widget: 'string'

          - label: 'Empty Cup'
            name: 'empty_cup'
            widget: 'string'

          - label: 'Cha Qi (body sensation, perspective alteration)'
            name: 'cha_qi'
            widget: 'string'

      - label: 'Preference Rating (0-100)'
        name: 'rating'
        widget: 'number'
        default: 50
        min: 0
        max: 100

      - label: 'Brewing Parameters'
        name: 'brewing'
        widget: 'object'
        collapsed: true
        fields:
          - label: 'Temp (°F)'
            name: 'temperature'
            widget: 'number'
            default: 200
            min: 0
            max: 705 # Just in case https://en.wikipedia.org/wiki/Superheated_water

          - label: 'Material Used (g)'
            name: 'material_amount'
            widget: 'number'
            default: 5
            min: 0

          - label: 'Liquid Amount (mL)'
            name: 'liquid_amount'
            widget: 'number'
            default: 100
            min: 0

          - label: 'First Infusion (s)'
            name: 'first_infusion_duration'
            widget: 'number'
            min: 0

          - label: 'General Increment (s)'
            name: 'infusion_increment'
            widget: 'number'
            min: 0

          - label: 'Vessel Type'
            name: 'vessel'
            widget: 'string'
            default: 'Porcelain Gaiwan'

      - label: 'Images'
        label_singular: 'Image'
        name: 'images'
        widget: 'list'
        summary: '{{fields.image}} - {{fields.alt}}'
        collapsed: true
        fields:
          - label: 'Image'
            name: 'image'
            widget: 'image'
          - label: 'Alt Text'
            name: 'alt'
            widget: 'string'

      - label: 'Body'
        name: 'body'
        widget: 'markdown'

  - label: 'Tea Genres'
    name: 'genres'
    label_singular: 'Tea Genre'
    description: 'The different teams in the game'
    folder: 'content/genres'
    create: true
    delete: true
    slug: '{{slug}}'
    identifier_field: 'name'
    summary: '{{fields.name}}'
    extension: 'md'
    sortable_fields: ['parent', 'color', 'name']
    view_filters:
      - label: 'Has Parent Type'
        field: parent
        pattern: '[0-9a-zA-Z]' # Match anything with legs

      - label: 'Base Type'
        field: parent
        pattern: '^(?![\s\S])' # Create a negative lookahead for any char
    view_groups:
      - label: 'Type:'
        field: parent
    fields:
      # - { label: 'ID', name: 'id', widget: 'id' }

      - label: 'Name'
        name: 'name'
        widget: 'string'

      - label: 'Category'
        name: 'parent'
        widget: 'relation'
        collection: 'genres'
        search_fields: ['name']
        value_field: 'name'
        display_fields: ['name']
        # summary: '{{fields.name}}'
        default: ''
        required: false

      - label: 'Color'
        name: 'color'
        widget: 'color'
        allowInput: true
        required: false

      - label: 'Description'
        name: 'description'
        widget: 'markdown'
        required: false

  - label: 'Cultivars'
    name: 'cultivars'
    label_singular: 'Tea Cultivar'
    description: 'The different teams in the game'
    folder: 'content/cultivars'
    create: true
    delete: true
    slug: '{{slug}}'
    identifier_field: 'name'
    summary: '{{author}} - {{commit_author}}'
    extension: 'md'
    fields:
      - label: 'Name'
        name: 'name'
        widget: 'string'

      - label: 'Description'
        name: 'description'
        widget: 'markdown'
        required: false

  - label: 'Origins'
    name: 'origins'
    label_singular: 'Tea Origin'
    description: 'Places around the tea world'
    folder: 'content/origins'
    create: true
    delete: true
    slug: '{{slug}}'
    identifier_field: 'name'
    summary: '{{author}} - {{commit_author}}'
    extension: 'md'
    fields:
      - label: 'Location'
        name: 'location'
        widget: 'string'
        required: false

      - label: 'Municipality'
        name: 'municipality'
        widget: 'string'
        required: false

      - label: 'Country'
        name: 'country'
        widget: 'string'
        required: false

      - label: 'Description'
        name: 'description'
        widget: 'markdown'
        required: false

  - label: 'Vendors'
    name: 'vendors'
    label_singular: 'Tea Vendor'
    description: 'Sellers of tea'
    folder: 'content/vendors'
    create: true
    delete: true
    slug: '{{slug}}'
    identifier_field: 'name'
    summary: '{{author}} - {{commit_author}}'
    extension: 'md'
    fields:
      - label: 'Vendor Name'
        name: 'name'
        widget: 'string'

      - label: 'Profile Picture'
        name: 'image'
        widget: 'image'

      - label: 'Links'
        label_singular: 'Link'
        name: 'links'
        widget: 'list'
        summary: '{{fields.website}}'
        allow_add: false
        collapsed: true
        required: false
        fields:
          - label: 'Website'
            name: 'website'
            widget: 'string'
            required: false

          - label: 'Instagram'
            name: 'instagram'
            widget: 'string'
            required: false

          - label: 'YouTube'
            name: 'youtube'
            widget: 'string'
            required: false

          - label: 'Facebook'
            name: 'facebook'
            widget: 'string'
            required: false

      - label: 'Location'
        name: 'location'
        widget: 'string'
        required: false

      - label: 'Municipality'
        name: 'municipality'
        widget: 'string'
        required: false

      - label: 'Country'
        name: 'country'
        widget: 'string'
        required: false

      - label: 'Description'
        name: 'description'
        widget: 'markdown'
        required: false
